services:
  - type: web
    name: innovation-imperial-portfolio
    env: node
    buildCommand: |
      echo "Starting build process..."
      npm ci
      echo "Running build..."
      npm run build
      echo "Build completed, checking directories..."
      pwd
      echo "Current directory contents:"
      ls -la
      
      echo "Checking dist directory contents:"
      ls -la dist/
      
      # Ensure the dist directory is in the correct location
      if [ ! -d "/opt/render/project/src/dist" ]; then
        echo "Moving dist directory to the correct location..."
        mkdir -p /opt/render/project/src/dist
        cp -r dist/* /opt/render/project/src/dist/
      fi
      
      if [ ! -f "/opt/render/project/src/dist/index.html" ]; then
        echo "Error: index.html not found in dist directory"
        exit 1
      fi
      
      echo "Final dist directory contents at /opt/render/project/src/dist:"
      ls -la /opt/render/project/src/dist/
      
      echo "Checking for JavaScript files in dist:"
      find /opt/render/project/src/dist -name "*.js" -type f
      echo "Checking for CSS files in dist:"
      find /opt/render/project/src/dist -name "*.css" -type f
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig.json
        - tsconfig.node.json
        - tsconfig.app.json
        - postcss.config.js
        - tailwind.config.ts
        - server.js
        - index.html
        - assets/** 