services:
  - type: web
    name: innovation-imperial-portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production 