services:
  - type: web
    name: innovation-imperial-portfolio
    env: node
    buildCommand: |
      npm ci
      npm run build
      ls -la
      ls -la dist
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig.json
        - tsconfig.node.json
        - server.js 