services:
  - type: web
    name: innovation-imperial-portfolio
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Node version:"
      node --version
      echo "NPM version:"
      npm --version
      
      # Clean install dependencies
      npm ci
      
      # Build the application
      echo "Running build..."
      npm run build
      
      echo "Build completed, checking build output..."
      pwd
      echo "Current directory contents:"
      ls -la
      
      echo "Checking dist directory contents:"
      ls -la dist/
      
      # Ensure the dist directory exists in both locations
      echo "Setting up dist directory in Render path..."
      mkdir -p /opt/render/project/src/dist
      cp -r dist/* /opt/render/project/src/dist/
      
      echo "Verifying dist directory contents:"
      echo "Local dist:"
      ls -la dist/
      echo "Render dist:"
      ls -la /opt/render/project/src/dist/
      
      # Verify index.html exists
      if [ ! -f "dist/index.html" ] || [ ! -f "/opt/render/project/src/dist/index.html" ]; then
        echo "Error: index.html not found in one or both dist directories"
        exit 1
      fi
      
      echo "Build verification complete. Contents of final dist directory:"
      ls -la /opt/render/project/src/dist/
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig.json
        - tsconfig.node.json
        - tsconfig.app.json
        - postcss.config.js
        - tailwind.config.ts
        - server.js
        - index.html
        - assets/** 