services:
  - type: web
    name: innovation-imperial-portfolio
    env: node
    buildCommand: |
      npm ci
      npm run build
      pwd
      echo "Build completed, checking dist directory..."
      ls -la
      if [ ! -d "dist" ]; then
        echo "dist directory not found, checking build output..."
        mkdir -p dist
        if [ -f "index.html" ]; then
          mv index.html dist/
        fi
        if [ -d "assets" ]; then
          mv assets dist/
        fi
      fi
      echo "Final dist directory contents:"
      ls -la dist/
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig.json
        - tsconfig.node.json
        - tsconfig.app.json
        - postcss.config.js
        - tailwind.config.ts
        - server.js 